### ISSUE TITLE
mask

### ISSUE THREAD

**Issue by 1234273** [nii-yamagishilab/Capsule-Forensics-v2#15]
Hi, I want to know that only FF++ database need to be pre-processed?
And when pre-processing, the mask maybe the face area? And how to get the mask, maybe label the original images?

**Comment by honghuy127** [comment]
Hi, all datasets need to be pre-processed to crop the face areas.

Different dataset may have different annotations for the face areas. For the FaceForensics++, annotations are the masks. Since face swapping methods were used in the FaceForensics++, we assumed that real faces and fake faces have the same positions. Therefore, we can use masks of fake faces for real faces. If other datasets do not have facial annotations, we need to perform face detection.

You can see the details in these [pre-processing scripts](https://github.com/nii-yamagishilab/Capsule-Forensics-v2/tree/master/datascripts) for the FaceForensics++.

**Comment by 1234273** [comment]
I got it.I have another question that whether cropping the face area needs to be done in both training and testing phases.

**Comment by 1234273** [comment]
Oh,I read the paper again.It need to do in training and testing phases,right?

**Comment by honghuy127** [comment]
Yes, you need to do the pre-processing on all sets (train, val, test).
